In [ ]:
import geopandas as gpd
from pathlib import Path

In [ ]:
RAW = r"S:\Tutorial\region-risk-atlas\regoin-risk-atlas\data\New_ward_45UTM\44-45_utm.shp"
# RAW = r"S:\Tutorial\region-risk-atlas\regoin-risk-atlas\data\boundaries\shapefiles\nepal_districts_wgs84.shp"

In [15]:
# help(gpd.read_file)

In [3]:
states = gpd.read_file(RAW)

In [4]:
print(len(states))

77

In [5]:
print(states.columns)

Index(['fid_1', 'FIRST_STAT', 'FIRST_DIST', 'FIRST_DCOD', 'Province',
       'geometry'],
      dtype='object')

In [6]:
states.head(5)

,fid_1,FIRST_STAT,FIRST_DIST,FIRST_DCOD,Province,geometry
0,1,7.0,ACHHAM,69,Sudurpashchim,"POLYGON ((81.17111 29.38643, 81.17146 29.38629..."
1,2,5.0,ARGHAKHANCHI,51,Lumbini,"POLYGON ((83.0044 28.11188, 83.00485 28.11177,..."
2,3,4.0,BAGLUNG,45,Gandaki,"POLYGON ((83.09957 28.63442, 83.10086 28.63401..."
3,4,7.0,BAITADI,74,Sudurpashchim,"POLYGON ((80.75833 29.70446, 80.75852 29.70422..."
4,5,7.0,BAJHANG,68,Sudurpashchim,"POLYGON ((81.08994 30.05411, 81.09021 30.0541,..."

In [21]:
print("Total Wards:", len(states))
# print("Districts:", states["DISTRICT"].unique().tolist())
print("Districts:", states["district"].unique().tolist())
print("States:", states["state_code"].unique().tolist())

Total Wards: 6803
Districts: ['KAILALI', 'DOLPA', 'SARLAHI', 'PALPA', 'MORANG', 'MAHOTTARI', 'KABHREPALANCHOK', 'KANCHANPUR', 'JHAPA', 'DHANUSHA', 'DADELDHURA', 'BARA', 'DARCHULA', 'ARGHAKHANCHI', 'BAITADI', 'BAJHANG', 'BAJURA', 'BHOJPUR', 'DHANKUTA', 'DOLAKHA', 'DOTI', 'JAJARKOT', 'JUMLA', 'KALIKOT', 'KHOTANG', 'LAMJUNG', 'MANANG', 'MUGU', 'MYAGDI', 'OKHALDHUNGA', 'PANCHTHAR', 'PARBAT', 'PYUTHAN', 'RASUWA', 'RUKUM_E', 'RUKUM_W', 'SALYAN', 'SANKHUWASABHA', 'SOLUKHUMBU', 'TAPLEJUNG', 'TERHATHUM', 'DAILEKH', 'LALITPUR', 'KAPILBASTU', 'BANKE', 'CHITAWAN', 'MAKAWANPUR', 'BHAKTAPUR', 'TANAHU', 'ACHHAM', 'SURKHET', 'UDAYAPUR', 'SINDHULI', 'SINDHUPALCHOK', 'SYANGJA', 'DHADING', 'GULMI', 'ILAM', 'GORKHA', 'NAWALPARASI_E', 'NAWALPARASI_W', 'NUWAKOT', 'KATHMANDU', 'KASKI', 'DANG', 'RAUTAHAT', 'RUPANDEHI', 'SAPTARI', 'SIRAHA', 'SUNSARI', 'BARDIYA', 'PARSA', 'BAGLUNG', 'MUSTANG', 'HUMLA', 'RAMECHHAP', 'ROLPA']
States: [7, 6, 2, 5, 1, 3, 4]

In [ ]:
STATE_NAME = "SAPTARI"
state_geom = states[states["DISTRICT"] == STATE_NAME]

print("Selected state:", STATE_NAME)

Selected state: SAPTARI

In [25]:
print(len(state_geom))

165

In [26]:
state_geom.head(5)

,OBJECTID,DCODE,DISTRICT,DAN,DAS,GaPa_NaPa,Type_GN,GN_CODE,NEW_WARD_N,DDGNWW,CENTER,STATE_CODE,DDGN,Area_SQKM,Shape_Leng,Shape_Area,VDC_Name,geometry
4340,4341,15,SAPTARI,None,0,Surunga,Nagarpalika,16.0,10,151610.0,None,2,15016,3.568269,11379.080961,3.568269e+06,None,"POLYGON ((453671.231 2946370.985, 453686.356 2..."
4341,4342,15,SAPTARI,None,0,Dakneshwori,Nagarpalika,7.0,5,150705.0,None,2,15007,7.369380,14140.006468,7.369380e+06,None,"POLYGON ((463246.049 2934288.208, 463254.109 2..."
4342,4343,15,SAPTARI,None,0,Dakneshwori,Nagarpalika,7.0,9,150709.0,None,2,15007,10.548828,17162.819889,1.054883e+07,None,"POLYGON ((468868.839 2939991.04, 468914.676 29..."
4343,4344,15,SAPTARI,None,0,Belhi Chapena,Gaunpalika,3.0,6,150306.0,None,2,15003,9.208679,20357.612533,9.208679e+06,None,"POLYGON ((469313.301 2932125.406, 469319.458 2..."
4344,4345,15,SAPTARI,None,0,Rajbiraj,Nagarpalika,12.0,11,151211.0,None,2,15012,4.471353,13353.329434,4.471353e+06,None,"POLYGON ((477973.98 2935513.956, 478056.124 29..."

In [7]:
OUT = Path("../data/boundaries")
OUT.mkdir(exist_ok=True)


# state_geom.to_file(OUT / "blocks_saptari.geojson", driver="GeoJSON")
states.to_file(OUT / "districts_nepal.geojson", driver="GeoJSON")

# print("STEP 1 COMPLETE — Saptari blocks exported")
print("STEP 1 COMPLETE — Nepal districts exported")

STEP 1 COMPLETE — Nepal districts exported

## Prepare geojson for GEE

In [8]:
import geopandas as gpd
from pathlib import Path

# blocks = gpd.read_file("../data/boundaries/blocks_saptari.geojson")
blocks = gpd.read_file("../data/boundaries/districts_nepal.geojson")

# Keep only essential fields
blocks = blocks.reset_index(drop=True)
blocks["block_id"] = blocks.index.astype(int)
# blocks = blocks[["block_id", "OBJECTID","GaPa_NaPa", "geometry"]]
blocks = blocks[["block_id","fid_1","FIRST_DIST","geometry"]]

# Save cleaned file for GEE
OUT = Path("../data/boundaries")
# blocks.to_file(OUT / "blocks_saptari_gee.geojson", driver="GeoJSON")
blocks.to_file(OUT / "districts_nepal_gee.geojson", driver="GeoJSON")

# print("Prepared districts_nepal_gee.geojson for GEE")
print("Prepared districts_nepal_gee.geojson for GEE")

Prepared districts_nepal_gee.geojson for GEE

### Create Shapefile for GEE Upload

In [25]:
import geopandas as gpd
from pathlib import Path

# Load GeoJSON
# gdf = gpd.read_file("../data/boundaries/blocks_saptari_gee.geojson")
gdf = gpd.read_file("../data/boundaries/blocks_nepal_gee.geojson")

# Output folder
# OUT = Path("../data/boundaries/saptari_bihar_shp")
OUT = Path("../data/boundaries/nepal_blocks_shp")
OUT.mkdir(exist_ok=True)

# Save as Shapefile
# gdf.to_file(OUT / "blocks_saptari.shp")
gdf.to_file(OUT / "blocks_nepal.shp")

print("Shapefile created for GEE upload")

Shapefile created for GEE upload